/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/gobot.glb 
*/

import React, {useEffect, useRef} from "react"
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/gobot.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names)

  useEffect(() => {
    actions[names[3]].reset().fadeIn(0.5).play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.FootL} />
          <primitive object={nodes.FootR} />
          <primitive object={nodes.Body} />
        </group>
        <group name="Gobot">
          <skinnedMesh name="GobotMesh" geometry={nodes.GobotMesh.geometry} material={materials.GobotMat} skeleton={nodes.GobotMesh.skeleton} />
          <skinnedMesh name="GobotMesh_1" geometry={nodes.GobotMesh_1.geometry} material={nodes.GobotMesh_1.material} skeleton={nodes.GobotMesh_1.skeleton} />
          <skinnedMesh name="GobotMesh_2" geometry={nodes.GobotMesh_2.geometry} material={nodes.GobotMesh_2.material} skeleton={nodes.GobotMesh_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('./models/gobot.glb')
